# This file was auto-generated by Fern from our API Definition.

from .types import GetContactCompaniesRequestOrderDirectionItem, PostContactCompaniesRequestPeopleItem

__all__ = ["GetContactCompaniesRequestOrderDirectionItem", "PostContactCompaniesRequestPeopleItem"]
