# This file was auto-generated by Fern from our API Definition.

import typing
import urllib.parse
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.jsonable_encoder import jsonable_encoder
from ..core.remove_none_from_dict import remove_none_from_dict
from ..not_found_error import NotFoundError
from ..unprocessable_entity_error import UnprocessableEntityError
from .get_income_invoices_request_order_direction_item import GetIncomeInvoicesRequestOrderDirectionItem
from .post_income_invoices_id_deliver_request_email import PostIncomeInvoicesIdDeliverRequestEmail
from .post_income_invoices_request_billing import PostIncomeInvoicesRequestBilling
from .post_income_invoices_request_custom_template import PostIncomeInvoicesRequestCustomTemplate
from .post_income_invoices_request_customer import PostIncomeInvoicesRequestCustomer
from .post_income_invoices_request_line_items_item import PostIncomeInvoicesRequestLineItemsItem
from .post_income_invoices_request_payment_term import PostIncomeInvoicesRequestPaymentTerm
from .put_income_invoices_id_request_billing import PutIncomeInvoicesIdRequestBilling
from .put_income_invoices_id_request_custom_template import PutIncomeInvoicesIdRequestCustomTemplate
from .put_income_invoices_id_request_customer import PutIncomeInvoicesIdRequestCustomer
from .put_income_invoices_id_request_line_items_item import PutIncomeInvoicesIdRequestLineItemsItem
from .put_income_invoices_id_request_payment_term import PutIncomeInvoicesIdRequestPaymentTerm

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class IncomeInvoiceRechnungClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_all_invoices(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        order_direction: typing.Optional[
            typing.Union[
                GetIncomeInvoicesRequestOrderDirectionItem, typing.List[GetIncomeInvoicesRequestOrderDirectionItem]
            ]
        ] = None,
        company_id: typing.Optional[int] = None,
        project_id: typing.Optional[int] = None,
        document_date_range_start: typing.Optional[str] = None,
        document_date_range_end: typing.Optional[str] = None,
    ) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - page: typing.Optional[int]. Page number

            - page_size: typing.Optional[int]. Page size (1-100)

            - order_by: typing.Optional[str]. Order by field (must be used with order_direction)

            - order_direction: typing.Optional[typing.Union[GetIncomeInvoicesRequestOrderDirectionItem, typing.List[GetIncomeInvoicesRequestOrderDirectionItem]]]. Order direction (must be used with order_by)

            - company_id: typing.Optional[int]. Filter by company id

            - project_id: typing.Optional[int]. Filter by project id

            - document_date_range_start: typing.Optional[str]. Filter by document date. Beginning of date range.

            - document_date_range_end: typing.Optional[str]. Filter by document date. End of date range.
        ---
        from feliche-93 import GetIncomeInvoicesRequestOrderDirectionItem
        from feliche-93.client import PapierkramClient

        client = PapierkramClient(token="YOUR_TOKEN", )
        client.income_invoice_rechnung.list_all_invoices(order_direction=GetIncomeInvoicesRequestOrderDirectionItem.ASC, )
        """
        _response = self._client_wrapper.httpx_client.request(
            "GET",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", "income/invoices"),
            params=remove_none_from_dict(
                {
                    "page": page,
                    "page_size": page_size,
                    "order_by": order_by,
                    "order_direction": order_direction,
                    "company_id": company_id,
                    "project_id": project_id,
                    "document_date_range_start": document_date_range_start,
                    "document_date_range_end": document_date_range_end,
                }
            ),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create_an_invoice(
        self,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        flagged: typing.Optional[bool] = OMIT,
        document_date: typing.Optional[str] = OMIT,
        supply_date: typing.Optional[str] = OMIT,
        customer: typing.Optional[PostIncomeInvoicesRequestCustomer] = OMIT,
        custom_template: typing.Optional[PostIncomeInvoicesRequestCustomTemplate] = OMIT,
        billing: typing.Optional[PostIncomeInvoicesRequestBilling] = OMIT,
        payment_term: PostIncomeInvoicesRequestPaymentTerm,
        line_items: typing.Optional[typing.List[PostIncomeInvoicesRequestLineItemsItem]] = OMIT,
    ) -> None:
        """
        Cost in API Credits: 50

        Parameters:
            - name: str.

            - description: typing.Optional[str].

            - flagged: typing.Optional[bool].

            - document_date: typing.Optional[str].

            - supply_date: typing.Optional[str].

            - customer: typing.Optional[PostIncomeInvoicesRequestCustomer].

            - custom_template: typing.Optional[PostIncomeInvoicesRequestCustomTemplate].

            - billing: typing.Optional[PostIncomeInvoicesRequestBilling].

            - payment_term: PostIncomeInvoicesRequestPaymentTerm.

            - line_items: typing.Optional[typing.List[PostIncomeInvoicesRequestLineItemsItem]].
        """
        _request: typing.Dict[str, typing.Any] = {"name": name, "payment_term": payment_term}
        if description is not OMIT:
            _request["description"] = description
        if flagged is not OMIT:
            _request["flagged"] = flagged
        if document_date is not OMIT:
            _request["document_date"] = document_date
        if supply_date is not OMIT:
            _request["supply_date"] = supply_date
        if customer is not OMIT:
            _request["customer"] = customer
        if custom_template is not OMIT:
            _request["custom_template"] = custom_template
        if billing is not OMIT:
            _request["billing"] = billing
        if line_items is not OMIT:
            _request["line_items"] = line_items
        _response = self._client_wrapper.httpx_client.request(
            "POST",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", "income/invoices"),
            json=jsonable_encoder(_request),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 422:
            raise UnprocessableEntityError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def retrieves_an_invoice(self, id: str) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice
        ---
        from feliche-93.client import PapierkramClient

        client = PapierkramClient(token="YOUR_TOKEN", )
        client.income_invoice_rechnung.retrieves_an_invoice(id="id", )
        """
        _response = self._client_wrapper.httpx_client.request(
            "GET",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}"),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 404:
            raise NotFoundError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def update_an_invoice(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        flagged: typing.Optional[bool] = OMIT,
        document_date: typing.Optional[str] = OMIT,
        supply_date: typing.Optional[str] = OMIT,
        customer: typing.Optional[PutIncomeInvoicesIdRequestCustomer] = OMIT,
        custom_template: typing.Optional[PutIncomeInvoicesIdRequestCustomTemplate] = OMIT,
        billing: typing.Optional[PutIncomeInvoicesIdRequestBilling] = OMIT,
        payment_term: typing.Optional[PutIncomeInvoicesIdRequestPaymentTerm] = OMIT,
        line_items: typing.Optional[typing.List[PutIncomeInvoicesIdRequestLineItemsItem]] = OMIT,
    ) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice

            - name: typing.Optional[str].

            - description: typing.Optional[str].

            - flagged: typing.Optional[bool].

            - document_date: typing.Optional[str].

            - supply_date: typing.Optional[str].

            - customer: typing.Optional[PutIncomeInvoicesIdRequestCustomer].

            - custom_template: typing.Optional[PutIncomeInvoicesIdRequestCustomTemplate].

            - billing: typing.Optional[PutIncomeInvoicesIdRequestBilling].

            - payment_term: typing.Optional[PutIncomeInvoicesIdRequestPaymentTerm].

            - line_items: typing.Optional[typing.List[PutIncomeInvoicesIdRequestLineItemsItem]].
        ---
        from feliche-93.client import PapierkramClient

        client = PapierkramClient(token="YOUR_TOKEN", )
        client.income_invoice_rechnung.update_an_invoice(id="id", )
        """
        _request: typing.Dict[str, typing.Any] = {}
        if name is not OMIT:
            _request["name"] = name
        if description is not OMIT:
            _request["description"] = description
        if flagged is not OMIT:
            _request["flagged"] = flagged
        if document_date is not OMIT:
            _request["document_date"] = document_date
        if supply_date is not OMIT:
            _request["supply_date"] = supply_date
        if customer is not OMIT:
            _request["customer"] = customer
        if custom_template is not OMIT:
            _request["custom_template"] = custom_template
        if billing is not OMIT:
            _request["billing"] = billing
        if payment_term is not OMIT:
            _request["payment_term"] = payment_term
        if line_items is not OMIT:
            _request["line_items"] = line_items
        _response = self._client_wrapper.httpx_client.request(
            "PUT",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}"),
            json=jsonable_encoder(_request),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 404:
            raise NotFoundError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        if _response.status_code == 422:
            raise UnprocessableEntityError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def delete_an_invoice(self, id: str) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice
        ---
        from feliche-93.client import PapierkramClient

        client = PapierkramClient(token="YOUR_TOKEN", )
        client.income_invoice_rechnung.delete_an_invoice(id="id", )
        """
        _response = self._client_wrapper.httpx_client.request(
            "DELETE",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}"),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 404:
            raise NotFoundError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def archive_an_invoice(self, id: str) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice
        ---
        from feliche-93.client import PapierkramClient

        client = PapierkramClient(token="YOUR_TOKEN", )
        client.income_invoice_rechnung.archive_an_invoice(id="id", )
        """
        _response = self._client_wrapper.httpx_client.request(
            "POST",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}/archive"),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def unarchive_an_invoice(self, id: str) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice
        ---
        from feliche-93.client import PapierkramClient

        client = PapierkramClient(token="YOUR_TOKEN", )
        client.income_invoice_rechnung.unarchive_an_invoice(id="id", )
        """
        _response = self._client_wrapper.httpx_client.request(
            "POST",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}/unarchive"),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def cancel_an_invoice(self, id: str) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice
        ---
        from feliche-93.client import PapierkramClient

        client = PapierkramClient(token="YOUR_TOKEN", )
        client.income_invoice_rechnung.cancel_an_invoice(id="id", )
        """
        _response = self._client_wrapper.httpx_client.request(
            "POST",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}/cancel"),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 422:
            raise UnprocessableEntityError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def deliver_an_invoice(
        self,
        id: str,
        *,
        send_via: typing.Optional[str] = OMIT,
        email: typing.Optional[PostIncomeInvoicesIdDeliverRequestEmail] = OMIT,
    ) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice

            - send_via: typing.Optional[str].

            - email: typing.Optional[PostIncomeInvoicesIdDeliverRequestEmail].
        ---
        from feliche-93.client import PapierkramClient

        client = PapierkramClient(token="YOUR_TOKEN", )
        client.income_invoice_rechnung.deliver_an_invoice(id="id", )
        """
        _request: typing.Dict[str, typing.Any] = {}
        if send_via is not OMIT:
            _request["send_via"] = send_via
        if email is not OMIT:
            _request["email"] = email
        _response = self._client_wrapper.httpx_client.request(
            "POST",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}/deliver"),
            json=jsonable_encoder(_request),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 422:
            raise UnprocessableEntityError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def retrieves_an_invoice_as_a_pdf(self, id: str) -> None:
        """
        Parameters:
            - id: str. The id of the invoice
        ---
        from feliche-93.client import PapierkramClient

        client = PapierkramClient(token="YOUR_TOKEN", )
        client.income_invoice_rechnung.retrieves_an_invoice_as_a_pdf(id="id", )
        """
        _response = self._client_wrapper.httpx_client.request(
            "GET",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}/pdf"),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncIncomeInvoiceRechnungClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_all_invoices(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        order_direction: typing.Optional[
            typing.Union[
                GetIncomeInvoicesRequestOrderDirectionItem, typing.List[GetIncomeInvoicesRequestOrderDirectionItem]
            ]
        ] = None,
        company_id: typing.Optional[int] = None,
        project_id: typing.Optional[int] = None,
        document_date_range_start: typing.Optional[str] = None,
        document_date_range_end: typing.Optional[str] = None,
    ) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - page: typing.Optional[int]. Page number

            - page_size: typing.Optional[int]. Page size (1-100)

            - order_by: typing.Optional[str]. Order by field (must be used with order_direction)

            - order_direction: typing.Optional[typing.Union[GetIncomeInvoicesRequestOrderDirectionItem, typing.List[GetIncomeInvoicesRequestOrderDirectionItem]]]. Order direction (must be used with order_by)

            - company_id: typing.Optional[int]. Filter by company id

            - project_id: typing.Optional[int]. Filter by project id

            - document_date_range_start: typing.Optional[str]. Filter by document date. Beginning of date range.

            - document_date_range_end: typing.Optional[str]. Filter by document date. End of date range.
        ---
        from feliche-93 import GetIncomeInvoicesRequestOrderDirectionItem
        from feliche-93.client import AsyncPapierkramClient

        client = AsyncPapierkramClient(token="YOUR_TOKEN", )
        await client.income_invoice_rechnung.list_all_invoices(order_direction=GetIncomeInvoicesRequestOrderDirectionItem.ASC, )
        """
        _response = await self._client_wrapper.httpx_client.request(
            "GET",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", "income/invoices"),
            params=remove_none_from_dict(
                {
                    "page": page,
                    "page_size": page_size,
                    "order_by": order_by,
                    "order_direction": order_direction,
                    "company_id": company_id,
                    "project_id": project_id,
                    "document_date_range_start": document_date_range_start,
                    "document_date_range_end": document_date_range_end,
                }
            ),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create_an_invoice(
        self,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        flagged: typing.Optional[bool] = OMIT,
        document_date: typing.Optional[str] = OMIT,
        supply_date: typing.Optional[str] = OMIT,
        customer: typing.Optional[PostIncomeInvoicesRequestCustomer] = OMIT,
        custom_template: typing.Optional[PostIncomeInvoicesRequestCustomTemplate] = OMIT,
        billing: typing.Optional[PostIncomeInvoicesRequestBilling] = OMIT,
        payment_term: PostIncomeInvoicesRequestPaymentTerm,
        line_items: typing.Optional[typing.List[PostIncomeInvoicesRequestLineItemsItem]] = OMIT,
    ) -> None:
        """
        Cost in API Credits: 50

        Parameters:
            - name: str.

            - description: typing.Optional[str].

            - flagged: typing.Optional[bool].

            - document_date: typing.Optional[str].

            - supply_date: typing.Optional[str].

            - customer: typing.Optional[PostIncomeInvoicesRequestCustomer].

            - custom_template: typing.Optional[PostIncomeInvoicesRequestCustomTemplate].

            - billing: typing.Optional[PostIncomeInvoicesRequestBilling].

            - payment_term: PostIncomeInvoicesRequestPaymentTerm.

            - line_items: typing.Optional[typing.List[PostIncomeInvoicesRequestLineItemsItem]].
        """
        _request: typing.Dict[str, typing.Any] = {"name": name, "payment_term": payment_term}
        if description is not OMIT:
            _request["description"] = description
        if flagged is not OMIT:
            _request["flagged"] = flagged
        if document_date is not OMIT:
            _request["document_date"] = document_date
        if supply_date is not OMIT:
            _request["supply_date"] = supply_date
        if customer is not OMIT:
            _request["customer"] = customer
        if custom_template is not OMIT:
            _request["custom_template"] = custom_template
        if billing is not OMIT:
            _request["billing"] = billing
        if line_items is not OMIT:
            _request["line_items"] = line_items
        _response = await self._client_wrapper.httpx_client.request(
            "POST",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", "income/invoices"),
            json=jsonable_encoder(_request),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 422:
            raise UnprocessableEntityError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def retrieves_an_invoice(self, id: str) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice
        ---
        from feliche-93.client import AsyncPapierkramClient

        client = AsyncPapierkramClient(token="YOUR_TOKEN", )
        await client.income_invoice_rechnung.retrieves_an_invoice(id="id", )
        """
        _response = await self._client_wrapper.httpx_client.request(
            "GET",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}"),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 404:
            raise NotFoundError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def update_an_invoice(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        flagged: typing.Optional[bool] = OMIT,
        document_date: typing.Optional[str] = OMIT,
        supply_date: typing.Optional[str] = OMIT,
        customer: typing.Optional[PutIncomeInvoicesIdRequestCustomer] = OMIT,
        custom_template: typing.Optional[PutIncomeInvoicesIdRequestCustomTemplate] = OMIT,
        billing: typing.Optional[PutIncomeInvoicesIdRequestBilling] = OMIT,
        payment_term: typing.Optional[PutIncomeInvoicesIdRequestPaymentTerm] = OMIT,
        line_items: typing.Optional[typing.List[PutIncomeInvoicesIdRequestLineItemsItem]] = OMIT,
    ) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice

            - name: typing.Optional[str].

            - description: typing.Optional[str].

            - flagged: typing.Optional[bool].

            - document_date: typing.Optional[str].

            - supply_date: typing.Optional[str].

            - customer: typing.Optional[PutIncomeInvoicesIdRequestCustomer].

            - custom_template: typing.Optional[PutIncomeInvoicesIdRequestCustomTemplate].

            - billing: typing.Optional[PutIncomeInvoicesIdRequestBilling].

            - payment_term: typing.Optional[PutIncomeInvoicesIdRequestPaymentTerm].

            - line_items: typing.Optional[typing.List[PutIncomeInvoicesIdRequestLineItemsItem]].
        ---
        from feliche-93.client import AsyncPapierkramClient

        client = AsyncPapierkramClient(token="YOUR_TOKEN", )
        await client.income_invoice_rechnung.update_an_invoice(id="id", )
        """
        _request: typing.Dict[str, typing.Any] = {}
        if name is not OMIT:
            _request["name"] = name
        if description is not OMIT:
            _request["description"] = description
        if flagged is not OMIT:
            _request["flagged"] = flagged
        if document_date is not OMIT:
            _request["document_date"] = document_date
        if supply_date is not OMIT:
            _request["supply_date"] = supply_date
        if customer is not OMIT:
            _request["customer"] = customer
        if custom_template is not OMIT:
            _request["custom_template"] = custom_template
        if billing is not OMIT:
            _request["billing"] = billing
        if payment_term is not OMIT:
            _request["payment_term"] = payment_term
        if line_items is not OMIT:
            _request["line_items"] = line_items
        _response = await self._client_wrapper.httpx_client.request(
            "PUT",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}"),
            json=jsonable_encoder(_request),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 404:
            raise NotFoundError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        if _response.status_code == 422:
            raise UnprocessableEntityError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def delete_an_invoice(self, id: str) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice
        ---
        from feliche-93.client import AsyncPapierkramClient

        client = AsyncPapierkramClient(token="YOUR_TOKEN", )
        await client.income_invoice_rechnung.delete_an_invoice(id="id", )
        """
        _response = await self._client_wrapper.httpx_client.request(
            "DELETE",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}"),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 404:
            raise NotFoundError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def archive_an_invoice(self, id: str) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice
        ---
        from feliche-93.client import AsyncPapierkramClient

        client = AsyncPapierkramClient(token="YOUR_TOKEN", )
        await client.income_invoice_rechnung.archive_an_invoice(id="id", )
        """
        _response = await self._client_wrapper.httpx_client.request(
            "POST",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}/archive"),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def unarchive_an_invoice(self, id: str) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice
        ---
        from feliche-93.client import AsyncPapierkramClient

        client = AsyncPapierkramClient(token="YOUR_TOKEN", )
        await client.income_invoice_rechnung.unarchive_an_invoice(id="id", )
        """
        _response = await self._client_wrapper.httpx_client.request(
            "POST",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}/unarchive"),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def cancel_an_invoice(self, id: str) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice
        ---
        from feliche-93.client import AsyncPapierkramClient

        client = AsyncPapierkramClient(token="YOUR_TOKEN", )
        await client.income_invoice_rechnung.cancel_an_invoice(id="id", )
        """
        _response = await self._client_wrapper.httpx_client.request(
            "POST",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}/cancel"),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 422:
            raise UnprocessableEntityError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def deliver_an_invoice(
        self,
        id: str,
        *,
        send_via: typing.Optional[str] = OMIT,
        email: typing.Optional[PostIncomeInvoicesIdDeliverRequestEmail] = OMIT,
    ) -> None:
        """
        Cost in API Credits: 1

        Parameters:
            - id: str. The id of the invoice

            - send_via: typing.Optional[str].

            - email: typing.Optional[PostIncomeInvoicesIdDeliverRequestEmail].
        ---
        from feliche-93.client import AsyncPapierkramClient

        client = AsyncPapierkramClient(token="YOUR_TOKEN", )
        await client.income_invoice_rechnung.deliver_an_invoice(id="id", )
        """
        _request: typing.Dict[str, typing.Any] = {}
        if send_via is not OMIT:
            _request["send_via"] = send_via
        if email is not OMIT:
            _request["email"] = email
        _response = await self._client_wrapper.httpx_client.request(
            "POST",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}/deliver"),
            json=jsonable_encoder(_request),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        if _response.status_code == 422:
            raise UnprocessableEntityError(pydantic.parse_obj_as(typing.Any, _response.json()))  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def retrieves_an_invoice_as_a_pdf(self, id: str) -> None:
        """
        Parameters:
            - id: str. The id of the invoice
        ---
        from feliche-93.client import AsyncPapierkramClient

        client = AsyncPapierkramClient(token="YOUR_TOKEN", )
        await client.income_invoice_rechnung.retrieves_an_invoice_as_a_pdf(id="id", )
        """
        _response = await self._client_wrapper.httpx_client.request(
            "GET",
            urllib.parse.urljoin(f"{self._client_wrapper.get_base_url()}/", f"income/invoices/{id}/pdf"),
            headers=self._client_wrapper.get_headers(),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
