# This file was auto-generated by Fern from our API Definition.

from .get_income_payment_terms_request_order_direction_item import GetIncomePaymentTermsRequestOrderDirectionItem

__all__ = ["GetIncomePaymentTermsRequestOrderDirectionItem"]
