repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        args: [--max-line-length=120]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        args:
          [--remove-unused-variables, --remove-all-unused-imports, --in-place]

  - repo: local
    hooks:
      - id: isort
        name: "Sort imports"
        language: system
        types: [file, python]
        entry: isort
        args: [--profile=black]
      - id: pylint
        name: "PyLint"
        language: system
        types: [python]
        files: ^(?!test_).*\.py$
        entry: python3 -m pylint
        args: [--errors-only]
      - id: black
        name: "Black"
        language: system
        pass_filenames: false
        entry: black .
        args:
          [--safe, --quiet, "--line-length=120", "--skip-string-normalization"]
