# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PutIncomePropositionsIdRequestPropositionType(str, enum.Enum):
    SERVICE = "service"
    PRODUCT = "product"
    ECOMMERCE = "ecommerce"

    def visit(
        self,
        service: typing.Callable[[], T_Result],
        product: typing.Callable[[], T_Result],
        ecommerce: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is PutIncomePropositionsIdRequestPropositionType.SERVICE:
            return service()
        if self is PutIncomePropositionsIdRequestPropositionType.PRODUCT:
            return product()
        if self is PutIncomePropositionsIdRequestPropositionType.ECOMMERCE:
            return ecommerce()
