# This file was auto-generated by Fern from our API Definition.

from .get_contact_companies_company_id_persons_request_order_direction_item import (
    GetContactCompaniesCompanyIdPersonsRequestOrderDirectionItem,
)

__all__ = ["GetContactCompaniesCompanyIdPersonsRequestOrderDirectionItem"]
