# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from .put_income_estimates_id_request_line_items_item_proposition import (
    PutIncomeEstimatesIdRequestLineItemsItemProposition,
)

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class PutIncomeEstimatesIdRequestLineItemsItem(pydantic.BaseModel):
    proposition: typing.Optional[PutIncomeEstimatesIdRequestLineItemsItemProposition]
    name: typing.Optional[str]
    description: typing.Optional[str]
    quantity: typing.Optional[float]
    unit: typing.Optional[str]
    vat_rate: typing.Optional[str]
    price: typing.Optional[float]
    start_new_item_group: typing.Optional[bool]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
