# This file was auto-generated by Fern from our API Definition.

from .get_contact_companies_request_order_direction_item import GetContactCompaniesRequestOrderDirectionItem
from .post_contact_companies_request_people_item import PostContactCompaniesRequestPeopleItem

__all__ = ["GetContactCompaniesRequestOrderDirectionItem", "PostContactCompaniesRequestPeopleItem"]
