# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class PostContactCompaniesRequestPeopleItem(pydantic.BaseModel):
    title: typing.Optional[str]
    salutation: typing.Optional[str]
    first_name: str
    last_name: str
    position: typing.Optional[str]
    department: typing.Optional[str]
    phone: typing.Optional[str]
    skype: typing.Optional[str]
    fax: typing.Optional[str]
    email: typing.Optional[str]
    flagged: typing.Optional[str]
    mobile: typing.Optional[str]
    comment: typing.Optional[str]
    default: typing.Optional[str]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
