find_relevant_keywords_task:
  description: >
    Identify the top relevant {num_results} search results for the keyword {keyword}.
  expected_output: >
    A list of relevant websites with their title and URL.

scrape_websites_task:
  description: >
    Scrape the {num_results} websites from the list of relevant websites.
  expected_output: >
    A list of scraped websites with their content, title, meta description, meta image, favicon, and body text.

extract_meta_information_task:
  description: >
    Extract the meta information from the scraped websites.
  expected_output: >
    A list of meta information with the title, meta description, meta image from a given scraped website.

find_info_about_person_task:
  description: >
    Find information about the person {person_name} on the internet.
  expected_output: >
    A list of bullet points of information about the person {person_name} on the internet.

